package platform

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/open-code-review/open-code-review/internal/model"
)

const (
	ocrBadge         = "![OpenCodeReview](https://img.shields.io/badge/OpenCodeReview-AI%20Review-1677ff)"
	ocrBadgeCritical = "![OpenCodeReview](https://img.shields.io/badge/OpenCodeReview-AI%20Review-critical)"
)

// extToLang maps common file extensions to Markdown code fence language identifiers.
var extToLang = map[string]string{
	".go":     "go",
	".py":     "python",
	".js":     "javascript",
	".ts":     "typescript",
	".tsx":    "tsx",
	".jsx":    "jsx",
	".java":   "java",
	".rs":     "rust",
	".rb":     "ruby",
	".c":      "c",
	".cpp":    "cpp",
	".cc":     "cpp",
	".h":      "c",
	".hpp":    "cpp",
	".cs":     "csharp",
	".swift":  "swift",
	".kt":     "kotlin",
	".scala":  "scala",
	".php":    "php",
	".lua":    "lua",
	".sh":     "bash",
	".bash":   "bash",
	".zsh":    "zsh",
	".sql":    "sql",
	".html":   "html",
	".css":    "css",
	".scss":   "scss",
	".json":   "json",
	".yaml":   "yaml",
	".yml":    "yaml",
	".toml":   "toml",
	".xml":    "xml",
	".md":     "markdown",
	".proto":  "protobuf",
	".tf":     "hcl",
	".vue":    "vue",
	".svelte": "svelte",
	".zig":    "zig",
	".dart":   "dart",
	".r":      "r",
	".ex":     "elixir",
	".exs":    "elixir",
	".erl":    "erlang",
	".hs":     "haskell",
	".ml":     "ocaml",
	".nim":    "nim",
	".v":      "verilog",
}

// codeFenceLanguage returns the Markdown code fence language identifier for
// a file path, based on its extension. Returns "text" for unknown extensions.
func codeFenceLanguage(path string) string {
	if path == "" {
		return "text"
	}
	ext := strings.ToLower(filepath.Ext(path))
	if lang, ok := extToLang[ext]; ok {
		return lang
	}
	return "text"
}

// RenderInlineComment renders a single inline comment body with the OCR inline marker.
func RenderInlineComment(c model.LlmComment) string {
	var b strings.Builder

	b.WriteString(ocrBadge + "\n\n")
	b.WriteString(strings.TrimSpace(c.Content))

	loc := formatLocation(c.Path, c.StartLine, c.EndLine)
	if loc != "" {
		fmt.Fprintf(&b, "\n\n**Location:** `%s`", loc)
	}

	if strings.TrimSpace(c.SuggestionCode) != "" {
		lang := codeFenceLanguage(c.Path)
		b.WriteString("\n\n**Suggested change:**\n```" + lang + "\n")
		b.WriteString(strings.TrimRight(c.SuggestionCode, "\n"))
		b.WriteString("\n```")
	}

	hasExisting := strings.TrimSpace(c.ExistingCode) != ""
	hasThinking := strings.TrimSpace(c.Thinking) != ""
	if hasExisting || hasThinking {
		b.WriteString("\n\n<details>\n<summary>Review context</summary>\n")
		if loc != "" {
			fmt.Fprintf(&b, "\nFile: %s", c.Path)
			if c.StartLine > 0 {
				if c.EndLine > c.StartLine {
					fmt.Fprintf(&b, "\nLines: %d-%d", c.StartLine, c.EndLine)
				} else {
					fmt.Fprintf(&b, "\nLine: %d", c.StartLine)
				}
			}
		}
		if hasExisting {
			lang := codeFenceLanguage(c.Path)
			b.WriteString("\n\nExisting code:\n\n```" + lang + "\n")
			b.WriteString(strings.TrimRight(c.ExistingCode, "\n"))
			b.WriteString("\n```")
		}
		if hasThinking {
			b.WriteString("\n\nReviewer notes:\n")
			b.WriteString(strings.TrimSpace(c.Thinking))
		}
		b.WriteString("\n</details>")
	}

	b.WriteString("\n\n<sub>Generated by OpenCodeReview.</sub>\n")
	b.WriteString(InlineMarker)

	return b.String()
}

// RenderSummaryComment renders the overall summary note body with the OCR summary marker.
func RenderSummaryComment(comments []model.LlmComment, warnings []PublishWarning) string {
	var b strings.Builder

	b.WriteString(ocrBadge + "\n\n")
	b.WriteString("## OpenCodeReview Summary\n\n")

	if len(comments) == 0 && len(warnings) == 0 {
		b.WriteString("No comments generated. Looks good to me.\n\n")
		b.WriteString(SummaryMarker)
		return b.String()
	}

	b.WriteString("Review completed.\n\n")
	fmt.Fprintf(&b, "- Review comments: %d\n", len(comments))
	if len(warnings) > 0 {
		fmt.Fprintf(&b, "- Inline comments not published: %d\n", len(warnings))
	}

	if len(comments) > 0 {
		b.WriteString("\n### Findings\n")
		limit := len(comments)
		if limit > 20 {
			limit = 20
		}
		for i := 0; i < limit; i++ {
			c := comments[i]
			loc := formatLocation(c.Path, c.StartLine, c.EndLine)
			first := firstLine(c.Content)
			if loc != "" {
				fmt.Fprintf(&b, "- `%s`: %s\n", loc, first)
			} else {
				fmt.Fprintf(&b, "- %s\n", first)
			}
		}
		if len(comments) > 20 {
			fmt.Fprintf(&b, "- ... and %d more\n", len(comments)-20)
		}
	}

	if len(warnings) > 0 {
		b.WriteString("\n<details>\n<summary>Publish diagnostics</summary>\n\n")
		for _, w := range warnings {
			if w.Path != "" {
				fmt.Fprintf(&b, "- `[%s] %s`: %s\n", w.Type, w.Path, w.Message)
			} else {
				fmt.Fprintf(&b, "- `[%s]`: %s\n", w.Type, w.Message)
			}
		}
		b.WriteString("\n</details>\n")
	}

	b.WriteString("\n")
	b.WriteString(SummaryMarker)
	return b.String()
}

// RenderRequestChangesComment renders a request-changes note body with the OCR request-changes marker.
func RenderRequestChangesComment(comments []model.LlmComment) string {
	var b strings.Builder

	b.WriteString(ocrBadgeCritical + "\n\n")
	b.WriteString("## OpenCodeReview found critical issues\n\n")

	for _, c := range comments {
		loc := formatLocation(c.Path, c.StartLine, c.EndLine)
		first := firstLine(c.Content)
		if loc != "" {
			fmt.Fprintf(&b, "- `%s`: %s\n", loc, first)
		} else {
			fmt.Fprintf(&b, "- %s\n", first)
		}
	}

	b.WriteString("\n")
	b.WriteString(RequestChangesMarker)
	return b.String()
}

// AppendOrReplaceManagedBlock appends or replaces the OCR managed summary block in an MR description.
// User text outside the marker block is never modified.
func AppendOrReplaceManagedBlock(description, summary string) string {
	block := PRSummaryStartMarker + "\n" + strings.TrimSpace(summary) + "\n" + PRSummaryEndMarker

	start := strings.Index(description, PRSummaryStartMarker)
	end := strings.Index(description, PRSummaryEndMarker)
	if start >= 0 && end >= start {
		end += len(PRSummaryEndMarker)
		prefix := strings.TrimSpace(description[:start])
		suffix := strings.TrimRight(description[end:], " \t")
		if suffix != "" && suffix[0] != '\n' {
			suffix = "\n\n" + strings.TrimSpace(suffix)
		}
		return prefix + "\n\n" + block + suffix
	}

	if strings.TrimSpace(description) == "" {
		return block
	}
	return strings.TrimSpace(description) + "\n\n---\n" + block
}

func formatLocation(path string, startLine, endLine int) string {
	if path == "" {
		return ""
	}
	if startLine <= 0 {
		return path
	}
	if endLine <= startLine {
		return fmt.Sprintf("%s:%d", path, startLine)
	}
	return fmt.Sprintf("%s:%d-%d", path, startLine, endLine)
}

func firstLine(s string) string {
	s = strings.TrimSpace(s)
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}
