package model

// Severity represents the severity level of a review comment.
type Severity string

const (
	SeverityCritical   Severity = "critical"
	SeverityWarning    Severity = "warning"
	SeveritySuggestion Severity = "suggestion"
	SeverityNitpick    Severity = "nitpick"
)

// SeverityRank returns an integer rank for ordering (higher = more severe).
func (s Severity) Rank() int {
	switch s {
	case SeverityCritical:
		return 4
	case SeverityWarning:
		return 3
	case SeveritySuggestion:
		return 2
	case SeverityNitpick:
		return 1
	default:
		return 0
	}
}

// ValidSeverity reports whether s is a recognized severity level.
func ValidSeverity(s string) bool {
	switch Severity(s) {
	case SeverityCritical, SeverityWarning, SeveritySuggestion, SeverityNitpick:
		return true
	}
	return false
}

// LlmComment represents a code review comment generated by the LLM.
type LlmComment struct {
	Path           string   `json:"path"`
	Content        string   `json:"content"`
	Severity       Severity `json:"severity,omitempty"`
	SuggestionCode string   `json:"suggestion_code,omitempty"`
	ExistingCode   string   `json:"existing_code,omitempty"`
	StartLine      int      `json:"start_line"`
	EndLine        int      `json:"end_line"`
	Thinking       string   `json:"thinking,omitempty"`
}

// CodeReviewResult holds raw LLM-generated review suggestion for a code segment.
type CodeReviewResult struct {
	RelevantFile      string `json:"relevant_file"`
	SuggestionContent string `json:"suggestion_content"`
	ExistingCode      string `json:"existing_code"`
	SuggestionCode    string `json:"suggestion_code"`
}
