// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 alibaba/open-code-review Contributors

package com.alibaba.opencodereview.idea.jcef

import com.alibaba.opencodereview.idea.model.HostStrings
import com.alibaba.opencodereview.idea.model.SupportedLocale
import com.alibaba.opencodereview.idea.model.toHtmlLang

/**
 * Assembles the HTML handed to JCEF. The JS is inlined instead of `<script src>`: loadHTML() has no base URL.
 * The lang attribute is kept -- the page's :lang() selectors and font fallback depend on it.
 */
object WebviewHtml {

    /** id of the `<style>` that carries the `--vscode-*` variables; theme switches locate it by this. */
    internal const val THEME_STYLE_ID = "ocr-theme"

    /** Sidebar page. [bridgeScript] is generated by `JBCefJSQuery.inject("json")`. */
    fun sidebar(locale: SupportedLocale, bridgeScript: String): String =
        page("/webview/webview.js", locale, bridgeScript)

    /** Config panel page. */
    fun configPanel(locale: SupportedLocale, bridgeScript: String): String =
        page("/webview/configPanel.js", locale, bridgeScript)

    private fun page(bundleResource: String, locale: SupportedLocale, bridgeScript: String): String {
        val bundle = readResource(bundleResource)
            ?: return missingBundle(bundleResource, locale)
        return buildPage(
            lang = locale.toHtmlLang(),
            themeCss = IdeaTheme.cssVariables(),
            bridgeScript = bridgeScript,
            bundleJs = bundle,
        )
    }

    /**
     * Pure string assembly, touches no UI, so it can be unit-tested directly.
     */
    internal fun buildPage(
        lang: String,
        themeCss: String,
        bridgeScript: String,
        bundleJs: String,
    ): String = buildString {
        append("<!DOCTYPE html>\n")
        append("<html lang=\"").append(lang).append("\">\n")
        append("<head>\n<meta charset=\"UTF-8\">\n")
        // Theme variables live in their own style element with a fixed id: on a theme switch only its textContent
        // is replaced, leaving the layout rules below untouched.
        // The id comes from THEME_STYLE_ID, and the Kotlin side builds its JS selector from the same constant, so
        // renaming the id cannot miss the selector.
        append("<style id=\"").append(THEME_STYLE_ID).append("\">\n")
        append(themeCss).append('\n')
        append("</style>\n<style>\n")
        append("html, body { margin: 0; padding: 0; height: 100%; overflow: hidden; }\n")
        append("#root { height: 100%; }\n")
        append("</style>\n</head>\n<body>\n")
        append("<div id=\"root\"></div>\n")
        // The bridge must be in place before the bundle: the page registers __ocrReceive as soon as it loads,
        // and __ocrPost must already exist by the time the page sends its ready message.
        append("<script>\nwindow.__ocrPost = function (json) { ")
        append(escapeForInlineScript(bridgeScript))
        append(" };\n</script>\n")
        append("<script>\n").append(escapeForInlineScript(bundleJs)).append("\n</script>\n")
        append("</body>\n</html>\n")
    }

    /**
     * A `</script` sequence inside an inline script is treated by the HTML parser as the end-of-script tag, and
     * the second half of the bundle would render as body text.
     * Minifier output is not stable, so escape unconditionally; `<\/script` is equivalent to the original inside
     * JS strings and regexes.
     *
     * **Note**: only the `</script>` sequence is handled, no HTML entity escaping; callers must pass trusted JS
     * (from the plugin's packaged bundle).
     */
    internal fun escapeForInlineScript(js: String): String =
        js.replace("</script", "<\\/script", ignoreCase = true)

    private fun readResource(path: String): String? {
        // Must be an absolute classpath path (starting with /): a relative path resolves against this class's
        // package, fails silently, and leaves only the fallback page -- very hard to troubleshoot.
        require(path.startsWith("/")) { "Resource path must be absolute: $path" }
        // runCatching: if readText throws IOException (an IO fault), return null so page()'s missingBundle fallback
        // kicks in instead of the exception escaping and crashing JCEF assembly.
        // Strip a leading UTF-8 BOM (U+FEFF); otherwise the inline JS starts with a BOM, which some engines misparse.
        return runCatching {
            javaClass.getResourceAsStream(path)?.bufferedReader(Charsets.UTF_8)?.use { it.readText() }
        }.getOrNull()?.removePrefix("\uFEFF")
    }

    /**
     * The bundle is not inside the jar (almost always because the frontend was not built). Copy goes through
     * [HostStrings] and must never be hardcoded: Chinese instructions on an English IDE would leave the user
     * unable to either read or act on them.
     */
    internal fun missingBundle(resource: String, locale: SupportedLocale): String = """
        <!DOCTYPE html>
        <html lang="${locale.toHtmlLang()}"><head><meta charset="UTF-8"></head>
        <body style="font-family: sans-serif; padding: 16px; line-height: 1.6">
        <h3>${HostStrings.t(locale, "ext.webview.missingBundleTitle")}</h3>
        <p>${HostStrings.t(locale, "ext.webview.missingBundleBody", "resource" to resource)}</p>
        <p>${HostStrings.t(locale, "ext.webview.missingBundleHint")}</p>
        <pre>cd frontend &amp;&amp; npm install &amp;&amp; npm run build</pre>
        <p>${HostStrings.t(locale, "ext.webview.missingBundleAlt")}</p>
        </body></html>
    """.trimIndent()
}
